[reticulum]
# Leave empty to use default Reticulum config (~/.reticulum)
configdir =

[client]
# Path to persist this client's RNS identity
identity_path = ./rproxy_client.id

# Seconds to wait for RNS link establishment
link_timeout = 15

# Seconds to wait for a fetch response from the proxy
request_timeout = 60

# Remove proxies from list if not re-announced within N seconds (0 = never)
proxy_ttl = 900

[webapp]
host  = 127.0.0.1
port  = 8585
debug = false
